DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  reference VARCHAR(255) UNIQUE,
  account_iban VARCHAR(34) NOT NULL,
  date TIMESTAMP,
  amount DECIMAL NOT NULL,
  fee DECIMAL,
  description VARCHAR(255),
  status VARCHAR(255),
  channel VARCHAR(255)
);

INSERT INTO TRANSACTION(amount, account_iban) VALUES (1, 'ES999999999999999999');

COMMIT;